# ==============================
# docker-compose.yml (전체 교체)
# ==============================

services:
  backend:
    container_name: bitflow-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./server:/app/server
      - ./server/static:/app/server/static:ro

  nginx:
    container_name: bitflow-nginx

    # [CHANGED] 컨텍스트를 프로젝트 루트로 변경
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: final-nginx

    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

    volumes:
      # [KEEP] conf 는 로컬 파일로 덮어써서 빠른 수정 가능
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      # [KEEP] LetsEncrypt 인증서 (HTTPS 사용 시)
      - /etc/letsencrypt:/etc/letsencrypt:ro

      # [KEEP] 스트리밍 파일 마운트 (백엔드가 생성해둔 세그먼트/MPD)
      - ./server/static:/srv/stream:ro

      # [REMOVED] ❌ dist 볼륨 마운트 (이미지에 bake된 정적파일을 호스트가 덮어쓰던 문제의 원인)
      # - ./Netflix/dist:/usr/share/nginx/html:ro
